// ============================================================
// FILE ELENCO STUDENTI
// REV. 2 — 30 giugno 2026
// Elenco reale: 245 studenti, Scuola Pol.G.A.I. Brescia
// Per modificare l'elenco, sostituisci semplicemente i nomi
// qui sotto, nello stesso formato.
// ============================================================

const STUDENTI = [
  "AGNELLO Salvatore Gabriele",
  "AIELLO Anthony",
  "ALIOTTA GAGLIANO Cristian",
  "ALLERI Matteo",
  "AMATO Simone Giovanni",
  "AMATO Vito Gabriele",
  "AMBRA Giovanni Carlo",
  "AMORE Carlo",
  "ANGILERI Giuseppe",
  "ARCIDIACONO Giorgio",
  "ARGIRDENI Daniele",
  "AUGELLO Samuele",
  "BAGLIO Francesco Paolo",
  "BALSAMO Martina",
  "BANFI Elviano Bruno",
  "BARRESI Alessia",
  "BATTAGLIA Alessio",
  "BATTIATO Alessio Antonino",
  "BELLANCA Enzo Pio",
  "BELLAVISTA Giovanni",
  "BETTEGA Roberto",
  "BIONDO Francesco",
  "BLUNDA Federico",
  "BONADONNA Giulio Savio",
  "BONO Davide",
  "BOZZA Alessia",
  "BRAMBATI Samuele",
  "BRISCHETTA Filippo",
  "BRUNO Giorgia",
  "BRUTTO Domenico",
  "CAUSA Martina",
  "CINA Greta",
  "BINDA Giorgio",
  "BONO Desiree",
  "BUBURUZANU Eusebiu Vasile",
  "CACI Emanuele",
  "CALTABIANO Riccardo Pio",
  "CAPRA Valerio Francesco",
  "CAPUTO Davide",
  "CARCANO Stefano Marco",
  "CARUSO Lorenzo",
  "CASSANELLI Filippo",
  "CASTELLANO Giovanni Mattia",
  "CASTIGLIONE Jacopo",
  "CATALANO Giovanni",
  "CATALANO Matteo",
  "CATALDO Andrea",
  "CHERUBINO Raffaele",
  "CIMINO Gabriele",
  "CIOCIOLA Micaela",
  "COCO Antonio Carmine",
  "CONSOLI Luca Federico",
  "CONTE Giorgia",
  "COPPOLA Giorgio",
  "COSENTINO Valerio",
  "COZZOLINO Giovanni",
  "COZZOLINO Jessica Michel",
  "D'ACHILLE Davide",
  "D'ARRIGO Cristian",
  "DEL DOSSO Giulia",
  "DELL'ORCO Pierpaolo",
  "DI BELLA Andrea",
  "D'IGNOTI Claudio",
  "FARABEGOLI Sofia",
  "BRAMBILLA Davide",
  "DI FAZIO Vincenzo",
  "DI GIUGNO Liborio",
  "DI LUCA CARDILLO Alessandro",
  "DI MARCO Francesco",
  "DIFRANCESCO Luca Pio",
  "DISTEFANO Samuele",
  "ERBA Angelo",
  "FABBRI Federico",
  "FALANGA Francesco Thomas",
  "FALETRA Matteo Pio",
  "FERRAMI Martina",
  "FERRARO Gaetano",
  "FERRARO Marco",
  "FICARRA Mattia",
  "FINOCCHIARO Giorgio Giovanni",
  "FIORILLO Michele",
  "FODERÀ Alessio",
  "FONTI Alessandro",
  "FRANCO Andrea",
  "FRATELLO Baldassare",
  "FRISON Luca",
  "GAGLIANO Giuseppe",
  "GALBUSERA Cristian",
  "GANDOLFO Samuele",
  "GENOVESE Sara",
  "GERACI Gaia",
  "GIACOLETTO Alba",
  "GRASSO Emma",
  "IADAROLA Giulia",
  "LOMONACO Simone",
  "GAROZZO Mattia",
  "GAZZO Daniele",
  "GELATI ALESSANDRO",
  "GENCO Stefano",
  "GENIO Antonino",
  "GENNARO Giuseppe Davide",
  "GENTILE Pietro",
  "GIANCONTIERI Andrea",
  "GIARRUSSO Mattia",
  "GINEVRA Roberto Pio",
  "GIORDANO Davide Maria",
  "GITTO Andrea",
  "GIUGNO Luigi",
  "GRAGLIA Tommaso",
  "GRANATA Riccardo",
  "GRECO Andrea",
  "GRECO Paolo",
  "GRECO Samuel",
  "GRIMAUDO Giuseppe",
  "GRUTTADAURIA Gabriele Savio",
  "GUALTIERI Valerio",
  "GUASTELLA Luca",
  "GURRISI Andrea",
  "GUSMEROLI Noemi",
  "KOUAI BARDI Aya",
  "MANFÈ Elena",
  "MANNINA Desirèe",
  "MANTEGAZZA Sara",
  "MARLETTA Giampiero",
  "MOLINARO Rebekka",
  "GUZZONE NEGLIA Giuseppe",
  "IMPERA Denise",
  "INDORATO Cristofaro",
  "INGARGIOLA Manuel",
  "INTRAVAIA Samuele",
  "IRACI Francesco",
  "ISTIKLALI Akram",
  "JONUZI Ander",
  "LA COMMARE Andrea",
  "LA FISCA Andrea",
  "LA ROCCA Alfredo",
  "LA VECCHIA Gioele",
  "LANZA Marco",
  "LI ROSI Davide",
  "LIUZZO Mattia Giuseppe",
  "LOMBARDO Andrea",
  "MACCARRONE Emanuele",
  "MANNINA Gabriele",
  "MARINO Matteo",
  "MATERIA Salvatore Giovanni",
  "MESSINA Concetto Gabriele",
  "MESSINA Roberto",
  "MOCCIARO Tommaso",
  "MOLÈ Alessandro",
  "MONACHINO Francesco",
  "MOTTADELLA Rebecca",
  "NAVETTA Francesco",
  "NEGLIA Maria Chiara",
  "OREFICE Sofia",
  "PARISI Megan",
  "LO PUMO Carmelo",
  "MONASTERI Francesco",
  "MONDIO Emanuele Pietro",
  "MONTAGNA Vincenzo",
  "MORI Nicolò",
  "MUSUMECI Alessandro",
  "NADILE Gabriele",
  "NAPOLITANO Vincenzo",
  "NATALE Gianfranco Paolo Maria",
  "NAVANZINO Saul",
  "NICOLACI Salvatore",
  "NSONDE BAZENGA Joel Uriel",
  "PAFFUTI Andrea",
  "PAGLIAZZO Roberto",
  "PALERMO Gabriele",
  "PALERMO Gaetano",
  "PALIO Giuseppe",
  "PASSANNANTE Davide Donato",
  "PATANÈ Giada",
  "PECORA Matteo",
  "PEPE Antonio",
  "PIACENTINO Mauro",
  "PIERANGIOLI Simone",
  "PILI Alessandro",
  "PIN Lorenzo",
  "PLANO Veronica",
  "RIZZO Pietro Gabriele",
  "ROMANO Carola",
  "RUBINO Ylenia",
  "SALEMI Marta",
  "BRIGANTE Gabriele",
  "PANIGHELLO Filippo",
  "PITONZO Matteo Salvatore",
  "PLACENTI Francesco Damiano",
  "PRIVITERA Graziano",
  "PROTO Davide",
  "PULTRONE Michele Nicola",
  "RALLO Vito",
  "RENDA Giovanni",
  "RICCOBENE Alessandro",
  "RICOTTA Giuseppe",
  "RIGGI Gianmarco",
  "RIVA Simone",
  "RIZZO Ettore",
  "ROTA Davide",
  "RUSSO Gaetano Davide",
  "RUSSO Michele",
  "RUSSO Michele",
  "SANFILIPPO Danilo",
  "SAURO Antonio Domenico",
  "SAVIANO Biagio",
  "SCARNERA Antonio",
  "SCARPINATO Roberta",
  "SCIARABBA Marta",
  "SCILABRA Michele",
  "SCIUTO Simone",
  "SCIVOLI Filippo",
  "SIHER Houda",
  "STARACE Gaia",
  "TOSONI Bianca",
  "RENDA Claudia",
  "SERINA Christian",
  "STABILE Davide",
  "STACCHIOTTI Alessio",
  "STAGNO Ignazio Manuel Pio",
  "SUMMA Gabriele",
  "TARDA Simone",
  "TOMASI Andrea",
  "TORRISI Giovanni",
  "TORRISI Vittorio",
  "TOSCANO Antonio",
  "TRAVAGLIANTI Francesco",
  "TRIPODI Giulia",
  "TROPEA Giuseppe Maria",
  "TRUPIA Giuseppe",
  "URSO Calogero Maria",
  "VANELLA Alberto Giuseppe",
  "VARCO Domenico Pio",
  "VAVASSORI Nicole",
  "VAZZOLER Marco Raffaele",
  "VELLA Rocco Davide",
  "VERÌ Jacopo",
  "VERZELETTI Micaela",
  "VICARIO Giorgia",
  "VIRGILIO Francesco Giuseppe",
  "VIRGILLITO Diego Maria",
  "VISCO Achille Antonio",
  "VITALE Mattia",
  "VOLO Salvatore",
  "ZAFFONTE Carlo",
];
